# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :pods do
    cocoapods()
  end

  desc "Description of what the lane does"
  lane :detox do
    build_app(
      workspace: "NucleusUiExample.xcworkspace",
      configuration: "Release",
      scheme: "NucleusUiExample",
      silent: true,
      clean: true,
      output_directory: "./build/ipa", # Destination directory. Defaults to current directory.
      output_name: "detox.ipa",       # specify the name of the .ipa file to generate (including file extension)
     derived_data_path: "./build/derive-data",
     sdk:"iphonesimulator"
    )
  end
end
