name: Build [Android]
on:
  workflow_dispatch: # To trigger manual build
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-app:
    name: Build android apk
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Git repository # clone the repo to local ci workspace
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - uses: actions/cache@v2
        name: Cache Node Modules
        with:
          path: |
            node_modules
            example/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install yarn dependencies
        run: |
          yarn install --frozen-lockfile
          yarn install --cwd example --frozen-lockfile

      - name: Build android app
        working-directory: example
        run: |
          yarn detox:build:android

      - name: Upload apk files
        uses: actions/upload-artifact@v3
        with:
          name: android-apks
          path: example/android/app/build/outputs/apk/*

  test-android-apk:
    name: Test android app
    runs-on: macos-latest
    needs:
      - build-app
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          path: example/android/app/build/outputs/apk
          name: android-apks

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - uses: actions/cache@v2
        name: Cache Node Modules
        with:
          path: |
            node_modules
            example/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ runner.ios }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          profile: 5.1in WVGA
          avd-name: 5.1_WVGA
          script: echo "Generated AVD snapshot for caching."


      - name: Install yarn dependencies
        run: |
          yarn install
          yarn install --cwd example


      - name: Test android app
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          profile: 5.1in WVGA
          avd-name: 5.1_WVGA
          script: cd example &&  yarn detox:test:android --headless

      - name: Upload diff screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: screenshots-diffs-android
          path: example/**/__diff_output__/*



